name: Reusable Build and manage version

on:
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        description: 'DOCKER_REGISTRY'
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        description: 'DOCKER_IMAGE_NAME'
        required: true
        type: string
      VERSION_FILE_NAME:
        description: 'File name with the version of the application'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: string
    secrets:

      SSH_PASSWORD:
        description: 'SSH_PASSWORD for deployment server'
        required: true
      SSH_IP:
        description: 'SSH_IP for deployment server'
        required: true 
      DOCKER_USERNAME:
        description: 'DOCKER_USERNAME'
        required: true
      DOCKER_PASSWORD:
        description: 'DOCKER_PASSWORD'
        required: true
      AZURE_STORAGE_ACCOUNT_NAME:
        description: 'AZURE_STORAGE_ACCOUNT_NAME'
        required: true
      AZURE_STORAGE_CONTAINER_NAME:
        description: 'AZURE_STORAGE_CONTAINER_NAME'
        required: true
      AZURE_STORAGE_SAS_TOKEN:
        description: 'AZURE_STORAGE_SAS_TOKEN'
        required: true
      EMBEDDING_MODEL:
        description: 'EMBEDDING_MODEL'
        required: true
      FIREWORKS_API_KEY:
        description: 'FIREWORKS_API_KEY'
        required: true
      FIREWORKS_MODEL:
        description: 'FIREWORKS_MODEL'
        required: true
      FW_API_KEY:
        description: 'FW_API_KEY'
        required: true
      FW_ENDPOINT:
        description: 'FW_ENDPOINT'
        required: true
      FW_MODEL:
        description: 'FW_MODEL'
        required: true
      LLAMAPARSE_API_KEY:
        description: 'LLAMAPARSE_API_KEY'
        required: true
      QDRANT_API_KEY:
        description: 'QDRANT_API_KEY'
        required: true
      QDRANT_URL:
        description: 'QDRANT_URL'
        required: true
      UNSTRUCTURED_API_KEY:
        description: 'UNSTRUCTURED_API_KEY'
        required: true
      UNSTRUCTURED_API_URL:
        description: 'UNSTRUCTURED_API_URL'
        required: true
      KAFKA_SCHEMA_REGISTRY_URL:
        description: 'KAFKA_SCHEMA_REGISTRY_URL'
        required: false
      KAFKA_SCHEMA_REGISTRY_API_KEY:
        description: 'KAFKA_SCHEMA_REGISTRY_API_KEY'  
        required: false
      KAFKA_SCHEMA_REGISTRY_API_SECRET:
        description: 'KAFKA_SCHEMA_REGISTRY_API_SECRET'
        required: false
      KAFKA_BOOTSTRAP:
        description: 'KAFKA_BOOTSTRAP'
        required: false
      KAFKA_SASL_USERNAME:
        description: 'KAFKA_SASL_USERNAME'
        required: false
      KAFKA_SASL_PASSWORD:
        description: 'KAFKA_SASL_PASSWORD'
        required: false
        
jobs:

  pre-build:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    outputs:
      version: ${{ steps.compute_version.outputs.version }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - id: compute_version
        shell: bash
        run: |
          ref="${GITHUB_REF_NAME}"
          if [ "$ref" = "develop" ]; then
            echo "version=latest-${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          elif [ "$ref" = "qa" ] || [ "$ref" = "staging" ]; then
            python3 /devops-tools/versionmanager.py increase ${{ inputs.VERSION_FILE_NAME}}
            export version=$(python3 /devops-tools/versionmanager.py get ${{ inputs.VERSION_FILE_NAME}})
            export version="$(echo "$version" | tr -d '\r' | xargs)"
            git config --global user.email "devops@achilles.com"
            git config --global user.name "Achilles DevOps Bot"
            git tag -a $version -m "Tag $version created automatically"
            git add .
            git commit -m "NOTICKET: Increasing version number"
            cat ${{ inputs.VERSION_FILE_NAME}}
            git push --tags
            git push origin $ref
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            echo "version=unknown" >> "$GITHUB_OUTPUT"
          fi

  build:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    needs: pre-build
    # environment: ${{ github.ref_name == 'develop' && 'development' || github.ref_name == 'staging' && 'staging' || github.ref_name == 'qa' && 'qa'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to custom Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.DOCKER_REGISTRY }} 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with dynamic tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ needs.pre-build.outputs.version }} # latest-${{ github.run_id }}
      - name: Run Trivy scan on private image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ needs.pre-build.outputs.version }}' # latest-${{ github.run_id }}'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'
          ignore-unfixed: true
          # vuln-type: 'os,library'
      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-json-report
          path: trivy-report.json

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests and generate reports
        run: |
          pytest tests/test_examples.py --junitxml=test-results.xml
          coverage run -m pytest tests/test_examples.py --junitxml=test-results.xml
          coverage xml -o coverage.xml
          coverage report
          bandit -r . -f json -o bandit-report.json || true

      - name: Upload XML files
        uses: actions/upload-artifact@v4
        with:
          name: xml-reports
          path: "*.xml"
          retention-days: 30
          if-no-files-found: warn    
      - name: Set up SonarQube project
        run: |
          # Create project and get token
          PROJECT_KEY="${{ github.event.repository.name }}"
          # Create project (using default admin credentials)
          curl -u admin:admin -X POST "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"
          echo "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"

          # Generate user token for analysis
          echo  "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}"
          curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions" -vvv
          TOKEN_RESPONSE=$(curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}")
          TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.token')
          echo "SONAR_TOKEN=${TOKEN}"
          echo "PROJECT_KEY=${PROJECT_KEY}"

          /github/workspace/sonar/bin/sonar-scanner \
            -Dsonar.projectKey=${PROJECT_KEY} \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${TOKEN} \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.python.xunit.reportPath=test-results.xml \
            -Dsonar.python.bandit.reportPaths=bandit-report.json \
            -Dsonar.exclusions=tests/**,venv/**,env/**,**/__pycache__/**
          sleep 30
          QUALITY_GATE=$(curl -u ${TOKEN}: "http://localhost:9000/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" | jq -r '.projectStatus.status')
        
          echo "Quality Gate Status: $QUALITY_GATE"       
          if [ "$QUALITY_GATE" != "OK" ]; then
            echo "Quality Gate failed!"
            echo "Ignoring errors for now, change next line to 'exit 1' to enforce quality gate."
            exit 0
          fi
  deploy:
    needs: [build, pre-build]
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    # if: ${{ vars.ENVIRONMENT_FROZEN == 'true'}} 
    steps:
      - run: |
          export DOCKER_REGISTRY=${{ inputs.DOCKER_REGISTRY }}
          export DOCKER_IMAGE_NAME=${{ inputs.DOCKER_IMAGE_NAME }}
          export VERSION=${{ needs.pre-build.outputs.version }}
          echo "${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${VERSION}"

          if [[ "${{ vars.ENVIRONMENT_FROZEN }}" == "true" ]]; then
            echo "Environment is frozen. Skipping deployment."
            exit 0
          fi
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -tt -o StrictHostKeyChecking=no neteng@${{ secrets.SSH_IP }} << 'EOF'

            echo "Running on remote machine..."
            echo "Releasing ${{ needs.pre-build.outputs.version }}"
            echo "Environment is frozen: ${{ vars.ENVIRONMENT_FROZEN }}"
            docker system prune -af

            docker login ${{ inputs.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd workspace

            # Remove old deployment directory if exists
            rm -rf ${{ github.event.repository.name }}

            # Clone fresh repository with latest code
            git clone git@github.com:${{ github.repository }}.git
            cd ${{ github.event.repository.name }}
            git checkout ${{ github.ref_name }}

            # Configure environment variables
            mv .env.example .env
            sed -i "s|QDRANT_URL=.*|QDRANT_URL=${{ secrets.QDRANT_URL }}|g" .env
            sed -i "s|QDRANT_API_KEY=.*|QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}|g" .env
            sed -i "s|EMBEDDING_MODEL=.*|EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}|g" .env

            perl -pi -e 's|^AZURE_STORAGE_SAS_TOKEN=.*|AZURE_STORAGE_SAS_TOKEN=${{ secrets.AZURE_STORAGE_SAS_TOKEN }}|g' .env
            sed -i "s|AZURE_STORAGE_ACCOUNT_NAME=.*|AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}|g" .env
            sed -i "s|AZURE_STORAGE_CONTAINER_NAME=.*|AZURE_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}|g" .env

            sed -i "s|UNSTRUCTURED_API_URL=.*|UNSTRUCTURED_API_URL=${{ secrets.UNSTRUCTURED_API_URL }}|g" .env
            sed -i "s|UNSTRUCTURED_API_KEY=.*|UNSTRUCTURED_API_KEY=${{ secrets.UNSTRUCTURED_API_KEY }}|g" .env

            sed -i "s|LLAMAPARSE_API_KEY=.*|LLAMAPARSE_API_KEY=${{ secrets.LLAMAPARSE_API_KEY }}|g" .env

            sed -i "s|FIREWORKS_API_KEY=.*|FIREWORKS_API_KEY=${{ secrets.FIREWORKS_API_KEY }}|g" .env
            sed -i "s|FIREWORKS_MODEL=.*|FIREWORKS_MODEL=${{ secrets.FIREWORKS_MODEL }}|g" .env

            sed -i "s|FW_API_KEY=.*|FW_API_KEY=${{ secrets.FW_API_KEY }}|g" .env
            sed -i "s|FW_ENDPOINT=.*|FW_ENDPOINT=${{ secrets.FW_ENDPOINT }}|g" .env
            sed -i "s|FW_MODEL=.*|FW_MODEL=${{ secrets.FW_MODEL }}|g" .env
            sed -i "s|DEBUG=.*|DEBUG=${{ vars.DEBUG }}|g" .env

            sed -i "s|DOCKER_REGISTRY=.*|DOCKER_REGISTRY=${{ inputs.DOCKER_REGISTRY }}|g" .env
            sed -i "s|DOCKER_IMAGE_NAME=.*|DOCKER_IMAGE_NAME=${{ inputs.DOCKER_IMAGE_NAME }}|g" .env
            sed -i "s|VERSION=.*|VERSION=${{ needs.pre-build.outputs.version }}|g" .env

            perl -pi -e 's|^KAFKA_SCHEMA_REGISTRY_URL=.*|KAFKA_SCHEMA_REGISTRY_URL=${{ secrets.KAFKA_SCHEMA_REGISTRY_URL }}|g' .env
            perl -pi -e 's|^KAFKA_SCHEMA_REGISTRY_API_KEY=.*|KAFKA_SCHEMA_REGISTRY_API_KEY=${{ secrets.KAFKA_SCHEMA_REGISTRY_API_KEY }}|g' .env
            perl -pi -e 's|^KAFKA_SCHEMA_REGISTRY_API_SECRET=.*|KAFKA_SCHEMA_REGISTRY_API_SECRET=${{ secrets.KAFKA_SCHEMA_REGISTRY_API_SECRET }}|g' .env
            sed -i "s|KAFKA_BOOTSTRAP=.*|KAFKA_BOOTSTRAP=${{ secrets.KAFKA_BOOTSTRAP }}|g" .env
            sed -i "s|KAFKA_SASL_USERNAME=.*|KAFKA_SASL_USERNAME=${{ secrets.KAFKA_SASL_USERNAME }}|g" .env
            sed -i "s|KAFKA_SASL_PASSWORD=.*|KAFKA_SASL_PASSWORD=${{ secrets.KAFKA_SASL_PASSWORD }}|g" .env

            cat .env
            export $(cat .env | xargs)

            # Create network if needed (using repository name as network name)
            NETWORK_NAME="${{ github.event.repository.name }}-network"
            if ! docker network inspect "${NETWORK_NAME}" >/dev/null 2>&1; then
              docker network create --driver bridge "${NETWORK_NAME}"
            fi

            # Pull the pre-built image from registry
            docker pull ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ needs.pre-build.outputs.version }}

            # Deploy using the pulled image (no rebuild)
            docker compose down --volumes --remove-orphans
            docker compose up -d
            exit 0
          EOF
      - run: echo "Deployment completed successfully!"